### ISSUE TITLE
Timeout errors?

### ISSUE THREAD

**Issue by RCheesley** [GrahamCampbell/Packagist-Stats#13]
Hi folks!

I've been using this recently to great effect to support our Open Startup reporting, but the last couple of months I'm struggling with running the same commands but getting the following error:

```
rcheesley@Drop local.packagiststats % ddev exec stats show mautic/api-library

In CurlFactory.php line 210:
                                                                                                                                                                                   
  cURL error 28: Resolving timed out after 10001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://packagist.org/packages/mautic/api-library.json  
                                                                                                                                                                                   

show [<vendors>...]

Failed to execute command stats show mautic/api-library: exit status 1
```

Wondered if maybe something has changed recently that might impact this but I've no idea where to start looking!

**Comment by GrahamCampbell** [comment]
I'm not able to replicate this. This looks like an DNS issue with your system.

**Comment by RCheesley** [comment]
Thanks, I had it for several months and then this month it started to work, no idea what was different but appreciate the reply!
