### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by irazasyed** [GrahamCampbell/Packagist-Stats#8]
I just installed this as a global package but the `stats` command isn't showing up. I checked for the `PATH` and composer bin is already there and I do have several other packages like Laravel installer and so on and they work fine.

I looked inside the global bin dir and there is no symlink to the bin dir of this package like it is for all other packages.

I checked your `composer.json` and there is no `bin` key with path to the executable either. Could that be an issue or what am I missing here or doing wrong?

**Comment by GrahamCampbell** [comment]
There is a bin key, but it doesn't seem to be working. I'd actually recommend the phar distribution tbh, rather than a global install, but I just never got around to updating the readme https://github.com/GrahamCampbell/Packagist-Stats/releases/download/v5.1.2/stats.phar.

**Comment by irazasyed** [comment]
No, you've defined `bin-dir` which is not the same as `bin` key. Please refer this, [How is it defined?](https://getcomposer.org/doc/articles/vendor-binaries.md#how-is-it-defined-)

I can send a PR if that's fine?

Check out [Laravel Installer](https://github.com/laravel/installer/blob/master/composer.json#L23-L25) for example.

**Comment by irazasyed** [comment]
Please merge and release #9?

**Comment by GrahamCampbell** [comment]
Fixed in v5.1.3.
